title: All I want to say...
author: Padmanabhan Subramanian
email: psone@live.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I enjoy learning and keep busy with C++ :)!
  Anything I learn, and believe would be useful, I share. Hope it helps someone.
  
# social links
#twitter_username: your-twitter-handle  DO NOT include the @ character, or else the build will fail!
github_username:  paddygit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

